### ISSUE TITLE
Not able to import this project

### ISSUE THREAD

**Issue by kirtihudda** [googleplus/gplus-quickstart-android#1]
Hello Sir,
I am trying to import this project in my eclipse by following the steps in https://developers.google.com/+/quickstart/android,but after downloading it as i tried to import this project,i got  "select at least one project"..i have download this 2-3 times but still facing the same problem.
please guide me how to import it..

Thanks & Regards
Kirti

**Comment by samtstern** [comment]
This repository is now deprecated, closing all issues.  See README.md for more information.
