### ISSUE TITLE
mSignInError

### ISSUE THREAD

**Issue by akhil2909** [googleplus/gplus-quickstart-android#10]
please help me to solve this error Google Play services error could not be resolved: 0 i.e.., mSignInError=0 and recives a toast msg "Google play service not available This application will be closed"

**Comment by RoneyThomas** [comment]
When you preview the app in emulator use android version with google play service.

**Comment by Kaushik1502** [comment]
Got the same error while I am testing the application in Moto g (2nd gen) having lollipop (5.0.2) any help will be appreciated thanks

**Comment by Kaushik1502** [comment]
http://i.imgur.com/PwOXHMI.png

**Comment by claywilkinson** [comment]
Can you post the log of when this is happening?

**Comment by Kaushik1502** [comment]
I had that in particular one phone I had checked if Google play services is
updated or not it was updated. Now that phone is not working properly so I
can't send you the log cat's error. After that I created new project and
run it. It was working on other devices but I couldn't test it on that
device. Can you please help me how can I store access token and use it in
future.

Thanks

**Comment by gguuss** [comment]
You typically should not be storing the access token on Android because it's short-lived.

**Comment by samtstern** [comment]
This repository is now deprecated, closing all issues.  See README.md for more information.
