### ISSUE TITLE
Sign-In Error when working with Web -client Id on Android!

### ISSUE THREAD

**Issue by monika-bindal** [googleplus/gplus-quickstart-android#21]
Hi,

We need ServerAuth Code and for that, we are using a web client id to request Server Auth code. Sometimes, it works fine but many times doesn't. If we create a new web client id, then it keeps giving Sign In Failed even though it show the user to select User account.

This is really critical for our app. Please figure this out.

Thanks

**Comment by samtstern** [comment]
This repository is now deprecated, closing all issues.  See README.md for more information.
