### ISSUE TITLE
NullPointerException when trying to logIn whithout internet connection.

### ISSUE THREAD

**Issue by knightmike** [googleplus/gplus-quickstart-android#3]
05-14 13:23:58.141: E/MoreInfoHPW_ViewGroup(15235): Parent view is not a TextView
05-14 13:23:58.187: D/dalvikvm(15235): GC_FOR_ALLOC freed 218K, 29% free 4319K/6072K, paused 30ms, total 30ms
05-14 13:23:58.187: I/dalvikvm-heap(15235): Grow heap (frag case) to 6.714MB for 1048592-byte allocation
05-14 13:23:58.219: D/dalvikvm(15235): GC_CONCURRENT freed 3K, 25% free 5339K/7100K, paused 8ms+2ms, total 35ms
05-14 13:23:58.219: D/dalvikvm(15235): WAIT_FOR_CONCURRENT_GC blocked 26ms
05-14 13:23:58.219: D/dalvikvm(15235): WAIT_FOR_CONCURRENT_GC blocked 25ms
05-14 13:23:58.477: D/dalvikvm(15235): GC_CONCURRENT freed 1113K, 37% free 4661K/7360K, paused 5ms+35ms, total 72ms
05-14 13:23:58.562: D/dalvikvm(15235): GC_FOR_ALLOC freed 129K, 36% free 4780K/7360K, paused 18ms, total 18ms
05-14 13:23:58.562: I/dalvikvm-heap(15235): Grow heap (frag case) to 7.240MB for 1127536-byte allocation
05-14 13:23:58.586: E/dalvikvm(15235): adjustAdaptiveCoef max=4194304, min=1048576, ut=568
05-14 13:23:58.586: D/dalvikvm(15235): GC_CONCURRENT freed <1K, 31% free 5881K/8464K, paused 2ms+1ms, total 23ms
05-14 13:23:58.586: D/dalvikvm(15235): WAIT_FOR_CONCURRENT_GC blocked 17ms
05-14 13:23:58.586: D/dalvikvm(15235): WAIT_FOR_CONCURRENT_GC blocked 16ms
05-14 13:23:58.617: D/AbsListView(15235): Get MotionRecognitionManager
05-14 13:23:58.656: D/AbsListView(15235): onVisibilityChanged() is called, visibility : 4
05-14 13:23:58.656: D/AbsListView(15235): unregisterIRListener() is called 
05-14 13:23:58.680: D/AbsListView(15235): onVisibilityChanged() is called, visibility : 0
05-14 13:23:58.680: D/AbsListView(15235): unregisterIRListener() is called 
05-14 13:23:58.758: D/libEGL(15235): loaded /vendor/lib/egl/libEGL_POWERVR_SGX540_120.so
05-14 13:23:58.773: D/libEGL(15235): loaded /vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so
05-14 13:23:58.773: D/libEGL(15235): loaded /vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so
05-14 13:23:58.914: D/OpenGLRenderer(15235): Enabling debug mode 0
05-14 13:23:58.914: D/AbsListView(15235): unregisterIRListener() is called 
05-14 13:23:58.992: I/android-plus-quickstart(15235): onConnectionFailed: ConnectionResult.getErrorCode() = 4
05-14 13:23:58.992: D/AbsListView(15235): unregisterIRListener() is called 
05-14 13:23:59.016: D/AbsListView(15235): unregisterIRListener() is called 
05-14 13:24:05.234: D/AbsListView(15235): unregisterIRListener() is called 
05-14 13:24:08.547: D/AbsListView(15235): unregisterIRListener() is called 
05-14 13:24:08.867: I/android-plus-quickstart(15235): onConnected
05-14 13:24:08.875: D/AndroidRuntime(15235): Shutting down VM
05-14 13:24:08.875: W/dalvikvm(15235): threadid=1: thread exiting with uncaught exception (group=0x41bde930)
05-14 13:24:08.883: E/AndroidRuntime(15235): FATAL EXCEPTION: main
05-14 13:24:08.883: E/AndroidRuntime(15235): java.lang.NullPointerException
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.plus.sample.quickstart.MainActivity.onConnected(MainActivity.java:223)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.internal.ei.b(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.common.api.b.dy(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.common.api.b.d(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.common.api.b$2.onConnected(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.internal.ei.b(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.internal.ei.bo(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.internal.eh$h.b(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.internal.eh$h.a(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.internal.eh$b.ec(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.google.android.gms.internal.eh$a.handleMessage(Unknown Source)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at android.os.Handler.dispatchMessage(Handler.java:99)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at android.os.Looper.loop(Looper.java:175)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at android.app.ActivityThread.main(ActivityThread.java:5279)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at java.lang.reflect.Method.invokeNative(Native Method)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at java.lang.reflect.Method.invoke(Method.java:511)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
05-14 13:24:08.883: E/AndroidRuntime(15235): 	at dalvik.system.NativeStart.main(Native Method)
05-14 13:24:20.172: I/Process(15235): Sending signal. PID: 15235 SIG: 9

**Comment by samtstern** [comment]
This repository is now deprecated, closing all issues.  See README.md for more information.
