### ISSUE TITLE
the code here and the official documentation are not in sync

### ISSUE THREAD

**Issue by mderazon** [googleplus/gplus-quickstart-android#5]
i'm wondering why simple login flow has to be so complicated and full of various callbacks, states and exception handling. so not intuitive 

is anyone even going through the issues here ?

more up to date examples would be helpful

**Comment by vipulyaara** [comment]
+1. The code mismatches the documentation and the workflow is really confusing. I implemented Facebook login in an hour while Google plus is taking weeks, especially revoking access while offline.

**Comment by samtstern** [comment]
This repository is now deprecated, closing all issues.  See README.md for more information.
